[workspace]
resolver = "3"
members = [ 
    "moqt-rs",
    "varintege-rs",
    "varintege-rs/varint_core", 
    "varintege-rs/varint_derive",
]

[workspace.dependencies]
bytes = "1.11"
indexmap = "2.12.0"
paste = "1"
pretty_assertions = "1.4.1"
snafu = "0.8.9"
