[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
moqt = { path = "../../moqt-rs", package = "moqt-rs" }
snafu = "0.8.9"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3.20"
